### ISSUE TITLE
Ajouter le nom du jour dans l'imprimé de la convocation

### ISSUE THREAD

**Issue by cdelmoni** [cdelmoni/mentorat_project#4]
Ajouter le nom du jour dans l'imprimé de la convocation

**Comment by basilgass** [comment]
Le nom du jour est maintenant mis (en français) dans les convocations. Par contre, j'ai introduit:

```
import locale
locale.setlocale(locale.LC_ALL, '')^
```

A priori, aucun risque, mais à contrôler à travers le code :)
