### ISSUE TITLE
Visualisation des renouvellement de contrats

### ISSUE THREAD

**Issue by cdelmoni** [cdelmoni/mentorat_project#5]
Il faut mettre en place une manière de visualiser si un contrat est le renouvellement d'un autre (existence d'un contrat parent) dans la liste des contrats (/contract/)

Idéalement, il faudrait pouvoir les regrouper en arborescence.

Faire de même dans les vues /eda/id/ et /mentor/id/

**Comment by basilgass** [comment]
Actuellement, cela fonctionne. Il faut que je fasse encore quelques ajustements...
Je dois encore gérer un peu les visuels, permettre de cacher les éléments passés / terminés ?
