### ISSUE TITLE
Statistiques annuelles

### ISSUE THREAD

**Issue by cdelmoni** [cdelmoni/mentorat_project#6]
Mettre en place un système de statistiques annuelles.
Voir avec Sandrine Amy pour les détails.

**Comment by basilgass** [comment]
C'est tout bon. Il y a un nouvel onglet statistiques qui permet de voir les informations suivantes:

le nombre d'étudiant.
le nombre de contrat
le nombre d'eda, mentors et contrat par branche (total, 1ère, 2ème, 3ème et 4ème année).

A voir s'il faut d'autres statistiques... Mais dans un premier temps, ça devrait le faire !
